/**
 * Messe Server API
 * API für die Messe-Anwendung
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DtoStockItem { 
    unitId?: number;
    articleNr?: string | null;
    articleDisplayName?: string | null;
    quantityUnits?: number;
    quantityBox?: number;
    quantityPerBox?: number;
    required?: number | null;
    updatedAt?: string;
}

