/**
 * Messe Server API
 * API für die Messe-Anwendung
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ort } from './ort';
import { ScanSessionType } from './scanSessionType';


export interface DtoScanSession { 
    id: number;
    startedAt: string;
    sessionType: ScanSessionType;
    ort: Ort;
    dispatchSheetId: number | null;
    updatedAt: string;
}
export namespace DtoScanSession {
}


