### ===== Trade Events =====
### Get all Trade Events
GET {{HostAddress}}/api/LoadingLists
Accept: application/json

### Get Trade Event by ID
GET {{HostAddress}}/api/LoadingLists/1
Accept: application/json

### Create new Trade Event
POST {{HostAddress}}/api/LoadingLists
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "name": "LKW-1"
}

### Update Trade Event
PUT {{HostAddress}}/api/LoadingLists/1
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "name": "LKW Groß"
}

### Delete Trade Event
DELETE {{HostAddress}}/api/LoadingLists/3
Accept: application/json

### Get LoadingLists articles
GET {{HostAddress}}/api/LoadingLists/1/units

### Set Required Units for Trade Event
POST {{HostAddress}}/api/LoadingLists/1/required-units
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "unitId": 6338,
  "count": 50
}

### Get Required Units for Trade Event
GET {{HostAddress}}/api/LoadingLists/1/required-units
Accept: application/json

### Update Required Units (different unit)
POST {{HostAddress}}/api/LoadingLists/1/required-units
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "unitId": 2,
  "count": 30
}

### Delete Required Unit (set count to 0)
POST {{HostAddress}}/api/LoadingLists/1/required-units
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "unitId": 1,
  "count": 0
}

### Delete Required Unit (using DELETE endpoint)
DELETE {{HostAddress}}/api/LoadingLists/1/required-units/2
Accept: application/json
