### Get article units
GET {{HostAddress}}/api/articles/units
Accept: application/json

### Import articles from JSON file
POST {{HostAddress}}/api/Articles/import
Content-Type: application/json; charset=utf-8
Accept: application/json

"C:\\Work\\github-herrmann\\hg-messe-app\\server\\messe-server\\testdata\\articles-with-units-20260111-135224.json"

### Get article by EAN
GET {{HostAddress}}/api/Articles/by-ean/4260165694551
Accept: application/json

### Get article by UnitId
GET {{HostAddress}}/api/Articles/1
Accept: application/json


### ===== Scan Sessions =====

### Get current Scan Session
GET {{HostAddress}}/api/ScanSessions/current
Accept: application/json

### Create new Scan Sessions
POST {{HostAddress}}/api/ScanSessions
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "tradeEventId": 1
}

### Get BarcodeScanner status
GET {{HostAddress}}/api/BarcodeScanner/status
Content-Type: application/json; charset=utf-8
Accept: application/json

