### Get articles
GET {{HostAddress}}/api/Articles
Accept: application/json

### Import articles from JSON file
POST {{HostAddress}}/api/Articles/import
Content-Type: application/json; charset=utf-8
Accept: application/json

"C:\\Work\\github-herrmann\\hg-messe-app\\server\\messe-server\\testdata\\articles-with-units-20260111-135224.json"
### Get article by EAN
GET {{HostAddress}}/api/Articles/by-ean/4260011990035
Accept: application/json

### Get article by UnitId
GET {{HostAddress}}/api/Articles/1
Accept: application/json

### List all EventInventories
GET {{HostAddress}}/api/EventInventories
Accept: application/json

### Get current EventInventory
GET {{HostAddress}}/api/EventInventories/current
Accept: application/json

### Create new EventInventory
POST {{HostAddress}}/api/EventInventories
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "tradeEventId": 1
}
### Test add stock to EventInventory
POST {{HostAddress}}/api/EventInventories/test
Content-Type: application/json; charset=utf-8
Accept: application/json

### Get stock of EventInventory
GET {{HostAddress}}/api/EventInventories/stock/1
Content-Type: application/json; charset=utf-8
Accept: application/json

### Get BarcodeScanner status
GET {{HostAddress}}/api/BarcodeScanner/status
Content-Type: application/json; charset=utf-8
Accept: application/json

###
